apiVersion: v1
kind: Service
metadata:
  name: backmarket-service
spec:
  type: NodePort
  selector:
    app: backmarket-app
  ports:
    - port: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backmarket-deployment
spec:
  selector:
    matchLabels:
      app: backmarket-app
  template:
    metadata:
      labels:
        app: backmarket-app
    spec:
      containers:
        - name: backmarket
          image: ghcr.io/samimiau/inventory:main
          imagePullPolicy: Always
          ports:
            - containerPort: 3000