services:
# levantar docker
  inventory: 
    build: .
    ports:
      - "5003:80"
    volumes:
      - .:/code
    links:
      - inventory_mongodb
  
  inventory_message_broker:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672


  # granja_inventory_events_receiver_02:
  #   build: .
  #   volumes:
  #     - .:/code
  #   links:
  #     - demo_04_service_02_mongodb
  #   command: python3 events.py

  #levanta mongo
  inventory_mongodb:
    image: mongo:5.0
    ports:
      - "5010:27017"
    volumes:
      - inventory_mongodb_container:/data/db
    logging:
        driver: none

volumes:
  inventory_mongodb_container:

# networks:
#   default:
#     name: granja
#     external: true